
package cn.howardliu.demo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FujiSyncWsServicePortType", targetNamespace = "http://ws.wfj.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FujiSyncWsServicePortType {
    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.wfj.com")
    @RequestWrapper(localName = "fujiSync", targetNamespace = "http://ws.wfj.com", className = "cn.howardliu.demo.ws.FujiSync")
    @ResponseWrapper(localName = "fujiSyncResponse", targetNamespace = "http://ws.wfj.com", className = "cn.howardliu.demo.ws.FujiSyncResponse")
    public String fujiSync(
        @WebParam(name = "in0", targetNamespace = "http://ws.wfj.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.wfj.com")
        String in1);

}
