
package cn.howardliu.demo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FujiSyncWsService", targetNamespace = "http://ws.wfj.com", wsdlLocation = "http://localhost:8080/MQInput/services/FujiSyncWsService?wsdl")
public class FujiSyncWsService
    extends Service
{

    private final static URL FUJISYNCWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUJISYNCWSSERVICE_EXCEPTION;
    private final static QName FUJISYNCWSSERVICE_QNAME = new QName("http://ws.wfj.com", "FujiSyncWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MQInput/services/FujiSyncWsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUJISYNCWSSERVICE_WSDL_LOCATION = url;
        FUJISYNCWSSERVICE_EXCEPTION = e;
    }

    public FujiSyncWsService() {
        super(__getWsdlLocation(), FUJISYNCWSSERVICE_QNAME);
    }

    public FujiSyncWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUJISYNCWSSERVICE_QNAME, features);
    }

    public FujiSyncWsService(URL wsdlLocation) {
        super(wsdlLocation, FUJISYNCWSSERVICE_QNAME);
    }

    public FujiSyncWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUJISYNCWSSERVICE_QNAME, features);
    }

    public FujiSyncWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FujiSyncWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FujiSyncWsServicePortType
     */
    @WebEndpoint(name = "FujiSyncWsServiceHttpPort")
    public FujiSyncWsServicePortType getFujiSyncWsServiceHttpPort() {
        return super.getPort(new QName("http://ws.wfj.com", "FujiSyncWsServiceHttpPort"), FujiSyncWsServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FujiSyncWsServicePortType
     */
    @WebEndpoint(name = "FujiSyncWsServiceHttpPort")
    public FujiSyncWsServicePortType getFujiSyncWsServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wfj.com", "FujiSyncWsServiceHttpPort"), FujiSyncWsServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUJISYNCWSSERVICE_EXCEPTION!= null) {
            throw FUJISYNCWSSERVICE_EXCEPTION;
        }
        return FUJISYNCWSSERVICE_WSDL_LOCATION;
    }

}
